# Generated by Django 3.1.7 on 2021-03-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0003_auto_20210223_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_text', models.CharField(max_length=50)),
                ('description_competence', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Discip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discip_title', models.CharField(max_length=50)),
                ('obyem_discip', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FormEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_education_title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GodNabora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god_nabora_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NapravPodgotovki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naprav_podgotovki_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya_prepod', models.CharField(max_length=20)),
                ('name_prepod', models.CharField(max_length=15)),
                ('otchestvo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ZUV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z', models.CharField(max_length=1000)),
                ('u', models.CharField(max_length=1000)),
                ('v', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='generator',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='generation_rpd.category', verbose_name='Категория'),
        ),
    ]
