# Generated by Django 3.1.7 on 2021-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0004_auto_20210320_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godnabora',
            name='god_nabora_num',
            field=models.CharField(max_length=10),
        ),
    ]
