# Generated by Django 3.1.7 on 2021-04-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0006_auto_20210331_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_b', models.CharField(max_length=10)),
            ],
        ),
    ]
