# Generated by Django 3.1.7 on 2021-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0008_auto_20210415_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_comp', models.CharField(max_length=10)),
                ('descrip_comp', models.TextField(blank=True, verbose_name='Формулировка компетенции')),
                ('kod_i_naim_comp', models.TextField(blank=True, verbose_name='Код и наименование индикатора достижения компеетенции')),
            ],
        ),
    ]
