# Generated by Django 3.1.7 on 2021-05-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0009_parscomp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parscomp',
            name='kod_i_naim_comp',
        ),
        migrations.AddField(
            model_name='parscomp',
            name='kod_i_naim_comp1',
            field=models.TextField(blank=True, verbose_name='Знать'),
        ),
        migrations.AddField(
            model_name='parscomp',
            name='kod_i_naim_comp2',
            field=models.TextField(blank=True, verbose_name='Владеть'),
        ),
    ]
