# Generated by Django 3.2 on 2021-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0012_selectcomp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetsAndTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(blank=True, verbose_name='Цели и задачи')),
                ('task', models.TextField(blank=True, verbose_name='Знать')),
                ('place_discip', models.TextField(blank=True, verbose_name='Знать')),
            ],
        ),
    ]
