# Generated by Django 3.2 on 2021-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0015_selectbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendBoook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, verbose_name='Библиографическая запись')),
            ],
        ),
    ]
