# Generated by Django 3.2 on 2021-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0017_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
                ('discip', models.CharField(max_length=300)),
            ],
        ),
    ]
