# Generated by Django 3.2 on 2021-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0018_prepinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepFIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
            ],
        ),
    ]
