# Generated by Django 3.2 on 2021-06-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0020_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
    ]
