# Generated by Django 3.2 on 2021-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0021_remove_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='role', max_length=10),
            preserve_default=False,
        ),
    ]
