# Generated by Django 3.2 on 2021-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation_rpd', '0022_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
            ],
        ),
    ]
